language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
before_script:
  - ln -s ./profiles/production.cfg production.cfg
  - ln -s ./profiles/development.cfg development.cfg
script:
  - buildout -c development.cfg
  - buildout -c production.cfg
#branches:
#  except:
#    - plone3.x
sudo: false
cache:
  directories:
    - eggs
